package com.example.aopzhujie.mapper;

import com.example.aopzhujie.model.AppCoopReport;
import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

@Mapper
public interface AppCoopReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_coop_report
     *
     * @mbg.generated Mon Feb 01 16:49:58 CST 2021
     */
    @Delete({
        "delete from app_coop_report",
        "where dim_date_id = #{dimDateId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String dimDateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_coop_report
     *
     * @mbg.generated Mon Feb 01 16:49:58 CST 2021
     */
    @Insert({
        "insert into app_coop_report (dim_date_id, channel_code, ",
        "channel, promo_type_code, ",
        "promo_type, offer_id, ",
        "dept, category, ",
        "fineline, upc, upc_desc, ",
        "city_code, city, ",
        "store_id, store_name, ",
        "cost_center, discount_code, ",
        "discount_type, vendor_nbr, ",
        "vendor_nbr9, vendor_name, ",
        "units, discount, ",
        "merch_sales, compensation_number, ",
        "compensation_ratio, compensation_total, ",
        "update_time)",
        "values (#{dimDateId,jdbcType=VARCHAR}, #{channelCode,jdbcType=VARCHAR}, ",
        "#{channel,jdbcType=VARCHAR}, #{promoTypeCode,jdbcType=VARCHAR}, ",
        "#{promoType,jdbcType=VARCHAR}, #{offerId,jdbcType=INTEGER}, ",
        "#{dept,jdbcType=VARCHAR}, #{category,jdbcType=VARCHAR}, ",
        "#{fineline,jdbcType=VARCHAR}, #{upc,jdbcType=VARCHAR}, #{upcDesc,jdbcType=VARCHAR}, ",
        "#{cityCode,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{storeId,jdbcType=INTEGER}, #{storeName,jdbcType=VARCHAR}, ",
        "#{costCenter,jdbcType=VARCHAR}, #{discountCode,jdbcType=VARCHAR}, ",
        "#{discountType,jdbcType=VARCHAR}, #{vendorNbr,jdbcType=VARCHAR}, ",
        "#{vendorNbr9,jdbcType=VARCHAR}, #{vendorName,jdbcType=VARCHAR}, ",
        "#{units,jdbcType=DECIMAL}, #{discount,jdbcType=DECIMAL}, ",
        "#{merchSales,jdbcType=DECIMAL}, #{compensationNumber,jdbcType=DECIMAL}, ",
        "#{compensationRatio,jdbcType=DECIMAL}, #{compensationTotal,jdbcType=DECIMAL}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(AppCoopReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_coop_report
     *
     * @mbg.generated Mon Feb 01 16:49:58 CST 2021
     */
//    int insertSelective(AppCoopReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_coop_report
     *
     * @mbg.generated Mon Feb 01 16:49:58 CST 2021
     */
    @Select({
        "select",
        "dim_date_id, channel_code, channel, promo_type_code, promo_type, offer_id, dept, ",
        "category, fineline, upc, upc_desc, city_code, city, store_id, store_name, cost_center, ",
        "discount_code, discount_type, vendor_nbr, vendor_nbr9, vendor_name, units, discount, ",
        "merch_sales, compensation_number, compensation_ratio, compensation_total, update_time",
        "from app_coop_report",
        "where dim_date_id = #{dimDateId,jdbcType=VARCHAR}"
    })
    @ResultMap("com.example.aopzhujie.mapper.appCoopReportMapper.BaseResultMap")
    AppCoopReport selectByPrimaryKey(String dimDateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_coop_report
     *
     * @mbg.generated Mon Feb 01 16:49:58 CST 2021
     */
//    int updateByPrimaryKeySelective(AppCoopReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_coop_report
     *
     * @mbg.generated Mon Feb 01 16:49:58 CST 2021
     */
    @Update({
        "update app_coop_report",
        "set channel_code = #{channelCode,jdbcType=VARCHAR},",
          "channel = #{channel,jdbcType=VARCHAR},",
          "promo_type_code = #{promoTypeCode,jdbcType=VARCHAR},",
          "promo_type = #{promoType,jdbcType=VARCHAR},",
          "offer_id = #{offerId,jdbcType=INTEGER},",
          "dept = #{dept,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=VARCHAR},",
          "fineline = #{fineline,jdbcType=VARCHAR},",
          "upc = #{upc,jdbcType=VARCHAR},",
          "upc_desc = #{upcDesc,jdbcType=VARCHAR},",
          "city_code = #{cityCode,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "store_id = #{storeId,jdbcType=INTEGER},",
          "store_name = #{storeName,jdbcType=VARCHAR},",
          "cost_center = #{costCenter,jdbcType=VARCHAR},",
          "discount_code = #{discountCode,jdbcType=VARCHAR},",
          "discount_type = #{discountType,jdbcType=VARCHAR},",
          "vendor_nbr = #{vendorNbr,jdbcType=VARCHAR},",
          "vendor_nbr9 = #{vendorNbr9,jdbcType=VARCHAR},",
          "vendor_name = #{vendorName,jdbcType=VARCHAR},",
          "units = #{units,jdbcType=DECIMAL},",
          "discount = #{discount,jdbcType=DECIMAL},",
          "merch_sales = #{merchSales,jdbcType=DECIMAL},",
          "compensation_number = #{compensationNumber,jdbcType=DECIMAL},",
          "compensation_ratio = #{compensationRatio,jdbcType=DECIMAL},",
          "compensation_total = #{compensationTotal,jdbcType=DECIMAL},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where dim_date_id = #{dimDateId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AppCoopReport record);

//    List<Map<String,Object>> getData();

}