package com.example.aopzhujie.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Course implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.platform
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Long status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.introduce
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.is_recommend
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Integer isRecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.gmt_create
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.gmt_modify
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cover_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private String coverPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.remark
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.creator
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.sort
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.buying_price
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private BigDecimal buyingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.study_person
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Integer studyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_classify
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private Long courseClassify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private String teacherPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.banner_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private String bannerPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.platform
     *
     * @return the value of course.platform
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withPlatform(String platform) {
        this.setPlatform(platform);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.platform
     *
     * @param platform the value for course.platform
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withStatus(Long status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.introduce
     *
     * @return the value of course.introduce
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withIntroduce(String introduce) {
        this.setIntroduce(introduce);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.introduce
     *
     * @param introduce the value for course.introduce
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.is_recommend
     *
     * @return the value of course.is_recommend
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withIsRecommend(Integer isRecommend) {
        this.setIsRecommend(isRecommend);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.is_recommend
     *
     * @param isRecommend the value for course.is_recommend
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.gmt_create
     *
     * @return the value of course.gmt_create
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withGmtCreate(Date gmtCreate) {
        this.setGmtCreate(gmtCreate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.gmt_create
     *
     * @param gmtCreate the value for course.gmt_create
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.gmt_modify
     *
     * @return the value of course.gmt_modify
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withGmtModify(Date gmtModify) {
        this.setGmtModify(gmtModify);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.gmt_modify
     *
     * @param gmtModify the value for course.gmt_modify
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cover_picture
     *
     * @return the value of course.cover_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public String getCoverPicture() {
        return coverPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withCoverPicture(String coverPicture) {
        this.setCoverPicture(coverPicture);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cover_picture
     *
     * @param coverPicture the value for course.cover_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setCoverPicture(String coverPicture) {
        this.coverPicture = coverPicture == null ? null : coverPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.remark
     *
     * @return the value of course.remark
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.remark
     *
     * @param remark the value for course.remark
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.creator
     *
     * @return the value of course.creator
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withCreator(Long creator) {
        this.setCreator(creator);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.creator
     *
     * @param creator the value for course.creator
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sort
     *
     * @return the value of course.sort
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withSort(Long sort) {
        this.setSort(sort);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sort
     *
     * @param sort the value for course.sort
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withPrice(BigDecimal price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.buying_price
     *
     * @return the value of course.buying_price
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public BigDecimal getBuyingPrice() {
        return buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withBuyingPrice(BigDecimal buyingPrice) {
        this.setBuyingPrice(buyingPrice);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.buying_price
     *
     * @param buyingPrice the value for course.buying_price
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setBuyingPrice(BigDecimal buyingPrice) {
        this.buyingPrice = buyingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.study_person
     *
     * @return the value of course.study_person
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Integer getStudyPerson() {
        return studyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withStudyPerson(Integer studyPerson) {
        this.setStudyPerson(studyPerson);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.study_person
     *
     * @param studyPerson the value for course.study_person
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setStudyPerson(Integer studyPerson) {
        this.studyPerson = studyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_classify
     *
     * @return the value of course.course_classify
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Long getCourseClassify() {
        return courseClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withCourseClassify(Long courseClassify) {
        this.setCourseClassify(courseClassify);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_classify
     *
     * @param courseClassify the value for course.course_classify
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setCourseClassify(Long courseClassify) {
        this.courseClassify = courseClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_picture
     *
     * @return the value of course.teacher_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public String getTeacherPicture() {
        return teacherPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withTeacherPicture(String teacherPicture) {
        this.setTeacherPicture(teacherPicture);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_picture
     *
     * @param teacherPicture the value for course.teacher_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setTeacherPicture(String teacherPicture) {
        this.teacherPicture = teacherPicture == null ? null : teacherPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.banner_picture
     *
     * @return the value of course.banner_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public String getBannerPicture() {
        return bannerPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public Course withBannerPicture(String bannerPicture) {
        this.setBannerPicture(bannerPicture);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.banner_picture
     *
     * @param bannerPicture the value for course.banner_picture
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    public void setBannerPicture(String bannerPicture) {
        this.bannerPicture = bannerPicture == null ? null : bannerPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Thu Dec 17 14:08:57 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", platform=").append(platform);
        sb.append(", status=").append(status);
        sb.append(", introduce=").append(introduce);
        sb.append(", isRecommend=").append(isRecommend);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append(", coverPicture=").append(coverPicture);
        sb.append(", remark=").append(remark);
        sb.append(", creator=").append(creator);
        sb.append(", sort=").append(sort);
        sb.append(", price=").append(price);
        sb.append(", buyingPrice=").append(buyingPrice);
        sb.append(", studyPerson=").append(studyPerson);
        sb.append(", courseClassify=").append(courseClassify);
        sb.append(", teacherPicture=").append(teacherPicture);
        sb.append(", bannerPicture=").append(bannerPicture);
        sb.append("]");
        return sb.toString();
    }
}